### ISSUE TITLE
Swiper Library is making the tests fail

### ISSUE THREAD

**Issue by wisammechano** [Recoded-Spark-Turkey-2022/Venus#46]
## Description
Swiper library is making jest fail when running tests due to unexpected import

```
Details:

    /workspace/Venus/node_modules/swiper/react/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './swiper-react.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { Swiper, SwiperSlide } from 'swiper/react';
        | ^
      3 | import { Pagination, Autoplay } from 'swiper';
      4 | import 'swiper/swiper-bundle.css';
      5 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/Reference.jsx:2:1)
      at Object.<anonymous> (src/pages/Home.jsx:4:1)
      at Object.<anonymous> (src/routes/AppRouter.jsx:4:1)
      at Object.<anonymous> (src/App.jsx:2:1)
      at Object.<anonymous> (src/App.test.js:5:1)
```

Either search for a library fix, or remove it to make test pass

## Steps to Reproduce

1. run `yarn test`

**Expected behavior:** 

Tests should pass

**Actual behavior:**
Tests are failing because CRA doesn't support pure ESM packages yet

https://swiperjs.com/react#usage-with-create-react-app

**Comment by dilaracetinberk** [comment]
We fixed it with using jest mock in our test pages.
